apiVersion: v1
kind: Pod
metadata:
  name: myapp
  labels:
    app: myapp
    any: thing
    you: want
spec:
  containers:
  - name: myapp
    image: metahertz/devnet-1999:latest
    env:
    - name: NODE_NAME
      valueFrom:
        fieldRef:
          fieldPath: spec.nodeName
    - name: POD_NAME
      valueFrom:
        fieldRef:
          fieldPath: metadata.name
    - name: POD_NAMESPACE
      valueFrom:
        fieldRef:
          fieldPath: metadata.namespace
    - name: POD_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
